name: fortnight-logs-clearing
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 1
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Hit the clear logs endpoint
        run: |
          curl --request DELETE \
          --url '${{ secrets.APP_CLEAR_LOGS_ENDPOINT }}' \
          --header 'x-app-service-id: ${{ secrets.APP_CLEAR_LOGS_CLIENT_ID }}'
